 <footer>
 	<div class="footer-links">
 		<ul>
 			<li><a href="#">Nav Item 1</a></li>
 			<li><a href="#">Nav Item 2</a></li>
 			<li><a href="#">Nav Item 3</a></li>
 			<li><a href="#">Nav Item 4</a></li>
 		</ul>
 	</div>
 	<div class="logo">
 	</div>
 	<div class="footer-links">
 		<p>Contact Us:</p>
 		<p>Email: <a href="mailto:info@example.com">info@example.com</a></p>
 		<p>Phone: +1 (123) 456-7890</p>
 	</div>
 </footer>